create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  gender text,
  region text,
  birth_year text,
  province text,
  note text,
  program text,
  created_at timestamptz default now() not null
);

alter table public.leads enable row level security;