"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, Check, ChevronLeft, ChevronRight, Clock3, MapPin, Menu, Phone, ShieldCheck, Star, Users, X } from "lucide-react";

const bannerImages = [
  "https://haiphongconnect.com.vn/wp-content/uploads/2026/08/chuong-trinh-xet-tuyen-di-nhat-ban-tai-hai-phong-connect-1.jpg",
  "https://haiphongconnect.com.vn/wp-content/uploads/2026/08/hai-phong-connect-dong-hanh-tren-con-duong-di-nhat-ban-1.jpg",
];

const programs = [
  ["CHƯƠNG TRÌNH SINGAPORE BẢO DƯỠNG, BẢO TRÌ, KIỂM TRA ĐỊNH KỲ Ô TÔ TẠI SINGAPORE", "Singapore", "34 Triệu ~ 39 Triệu/Tháng", "https://haiphongconnect.com.vn/wp-content/uploads/2026/07/chuong-trinh-japan-bao-duong-bao-tri-kiem-tra-dinh-ki-o-to-tai-nhat-ban.jpg"],
  ["CHƯƠNG TRÌNH TOKAI SẢN XUẤT BÊ TÔNG TẠI SINGAPORE", "Singapore", "29 Triệu - 37 Triệu/Tháng", "https://haiphongconnect.com.vn/wp-content/uploads/2026/07/chuong-trinh-tokai-san-xuat-be-tong-tai-nhat-ban.jpg"],
  ["CHƯƠNG TRÌNH RYOBI BẢO DƯỠNG SỬA CHỮA Ô TÔ TẠI SINGAPORE", "Singapore", "40 Triệu ~ 50 Triệu/Tháng", "https://haiphongconnect.com.vn/wp-content/uploads/2026/07/chuong-tinh-ryobi-bao-duong-sua-chua-o-to-tai-nhat-ban.jpg"],
  ["CHƯƠNG TRÌNH WAITEKKU VẬN HÀNH ROBOT HÀN VÀ KIỂM TRA LINH KIỆN", "Singapore", "31 Triệu ~ 40 Triệu/Tháng", "https://haiphongconnect.com.vn/wp-content/uploads/2026/06/chuong-trinh-weitekku-van-hanh-thac-tac-robot-han-va-kiem-tra-linh-kien-san-pham-tai-nhat-ban.jpeg"],
  ["CHƯƠNG TRÌNH SINGAPORE ĐIỀU DƯỠNG TẠI CÁC BỆNH VIỆN VỚI CHI PHÍ 0Đ", "Singapore", "32 Triệu ~ 40 Triệu/Tháng", "https://haiphongconnect.com.vn/wp-content/uploads/2026/07/chuong-trinh-japan-dieu-duong-o-cac-benh-vien-tai-nhat-ban-voi-chi-phi-0d.jpeg"],
  ["CHƯƠNG TRÌNH SKM VỆ SINH TÒA NHÀ, KHÁCH SẠN VỚI CHI PHÍ 0Đ", "Singapore", "29 Triệu ~ 39 Triệu/Tháng", "https://haiphongconnect.com.vn/wp-content/uploads/2026/07/chuong-trinh-skm-ve-sinh-toa-nha-khach-san-tai-nhat-ban-voi-chi-phi-0d.jpg"],
];

const strengths = [
  ["Đào tạo bài bản, nội trú 4–6 tháng", "Trung tâm đào tạo nội trú riêng tại Hà Nội với giáo viên người Singapore, chuẩn bị đầy đủ kỹ năng, tiếng Anh và văn hóa trước khi xuất cảnh."],
  ["Xuất cảnh đúng hẹn, không trì hoãn", "98% đơn hàng xuất cảnh đúng hoặc sớm hơn lịch hẹn. Không có chuyện đợi mãi không thấy ngày bay."],
  ["Hợp đồng minh bạch, không phát sinh phí", "Mọi khoản phí được niêm yết và ký hợp đồng từ đầu. Cam kết không thu thêm bất kỳ khoản nào ngoài danh sách đã công bố."],
  ["Văn phòng đại diện tại Singapore", "Có văn phòng tại Singapore, đội ngũ người Việt hỗ trợ 24/7 khi bạn gặp khó khăn."],
  ["Hơn 500 đối tác xí nghiệp uy tín", "Mạng lưới rộng khắp Singapore, đa dạng ngành nghề từ cơ khí, xây dựng đến chế biến thực phẩm, điều dưỡng."],
  ["Hỗ trợ trọn đời sau hợp đồng", "Tư vấn tái ký, chuyển việc, gia hạn visa, chuẩn bị về nước. Học viên Jinmu là gia đình Jinmu."],
];

const roadmap = ["Tư vấn & sơ tuyển miễn phí", "Khám sức khỏe", "Phỏng vấn chương trình", "Trúng tuyển – Ký hợp đồng", "Đào tạo nội trú 4–6 tháng", "Hoàn tất hồ sơ – Xin visa", "Xuất cảnh", "Đồng hành tại Singapore"];

function LeadForm({ compact = false, onSuccess }: { compact?: boolean; onSuccess: () => void }) {
  const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true);
    const data = Object.fromEntries(new FormData(event.currentTarget));
    await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) });
    setLoading(false); event.currentTarget.reset(); onSuccess();
  }
  return <form className={compact ? "lead-form modal-form" : "lead-form"} onSubmit={submit}>
    <div className="form-row"><input required name="name" placeholder="Họ và tên *" /><input required name="phone" type="tel" placeholder="Số điện thoại *" /></div>
    <div className="form-row"><input name="email" type="email" placeholder="Email" /><select required name="gender" defaultValue=""><option value="" disabled>Giới tính *</option><option>Nam</option><option>Nữ</option></select></div>
    <div className="form-row"><select required name="region" defaultValue=""><option value="" disabled>Miền *</option><option>Bắc</option><option>Trung</option><option>Nam</option></select><input required name="birth_year" inputMode="numeric" maxLength={4} placeholder="Năm sinh *" /></div>
    <input required name="province" placeholder="Tỉnh/thành của bạn *" /><textarea name="note" rows={3} placeholder="Nội dung tư vấn (ngành nghề, độ tuổi, kinh nghiệm…)" />
    <label className="consent"><input required name="consent" type="checkbox" defaultChecked /> <span>Tôi đồng ý cho phép Jinmu xử lý dữ liệu cá nhân theo <u>Chính sách bảo mật</u>.</span></label>
    <button className="button button-green full" disabled={loading}>{loading ? "Đang gửi..." : compact ? "ĐĂNG KÝ TƯ VẤN NGAY" : "Nhận Tư Vấn"} <ArrowRight size={17} /></button>
  </form>;
}

export default function Home() {
  const [slide, setSlide] = useState(0); const [menu, setMenu] = useState(false); const [modal, setModal] = useState(false); const [success, setSuccess] = useState(false);
  useEffect(() => { const timer = setInterval(() => setSlide((value) => (value + 1) % bannerImages.length), 5000); return () => clearInterval(timer); }, []);
  function openModal() { setSuccess(false); setModal(true); }
  return <main>
    <header className="source-header"><div className="container source-nav"><a className="source-logo" href="#top"><span>JINMU</span><b>JINMU</b></a><nav className={menu ? "source-links show" : "source-links"}><a href="#programs">Chương trình</a><a href="#cost">Chi phí</a><a href="#roadmap">Quy trình</a><button onClick={openModal}>Đăng ký tư vấn</button></nav><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Mở menu">{menu ? <X /> : <Menu />}</button></div></header>
    <section className="source-title" id="top"><div className="container"><h1>ĐI LÀM TẠI SINGAPORE CÙNG JINMU</h1></div></section>
    <section className="banner-section"><div className="container"><div className="banner-frame"><img src={bannerImages[slide]} alt="Chương trình đi Singapore tại Jinmu" /><button className="banner-arrow left" onClick={() => setSlide((slide + 1) % 2)} aria-label="Ảnh trước"><ChevronLeft /></button><button className="banner-arrow right" onClick={() => setSlide((slide + 1) % 2)} aria-label="Ảnh sau"><ChevronRight /></button><div className="dots">{bannerImages.map((_, index) => <button key={index} className={slide === index ? "active" : ""} onClick={() => setSlide(index)} aria-label={`Slide ${index + 1}`} />)}</div></div></div></section>
    <section className="registration"><div className="container"><div className="registration-head"><span className="kicker">Nhận tư vấn</span><h2>Chương Trình Đi Singapore Hấp Dẫn</h2><p>Các chuyên viên Jinmu sẽ liên hệ ngay với bạn</p></div><div className="registration-grid"><div className="form-card"><LeadForm onSuccess={() => setSuccess(true)} />{success && <div className="inline-success"><Check size={18} /> Cảm ơn! Chúng tôi sẽ liên hệ lại trong vòng 24 giờ.</div>}</div><div className="form-aside"><img src="https://haiphongconnect.com.vn/wp-content/uploads/2026/06/729186450_122185815974712378_8695870803602476120_n.jpg" alt="Học viên Jinmu" /><span>Thực tập sinh Điều dưỡng viên</span><strong>CƠ HỘI ĐI SINGAPORE<br />CHI PHÍ 0Đ</strong></div></div></div></section>
    <section className="trust"><div className="container"><h2>Gần 20 Năm Đồng Hành Cùng Người Lao Động Việt</h2><div className="trust-grid"><div><Star /><b>Gần 20</b><span>Năm kinh nghiệm xuất khẩu lao động</span></div><div><Users /><b>20.000+</b><span>Lao động đã xuất cảnh thành công</span></div><div><ShieldCheck /><b>500+</b><span>Đối tác xí nghiệp Singapore</span></div><div><Check /><b>98%</b><span>Tỷ lệ xuất cảnh đúng hẹn</span></div></div></div></section>
    <section className="source-section compare"><div className="container"><h2>Đi Singapore Không Chỉ Là Chọn Một Đơn Hàng</h2><p className="section-intro">Quyết định đi Singapore là quyết định lớn cho 3-5 năm tương lai. Hãy so sánh để chọn đúng đơn vị đồng hành.</p><div className="comparison"><div className="comparison-row heading"><b>Tiêu chí</b><b>Jinmu</b><b>Đơn vị khác</b></div>{[["Chi phí", "Minh bạch từ đầu, có hợp đồng rõ ràng", "Phát sinh nhiều khoản phụ phí"], ["Đào tạo", "Nội trú 4-6 tháng, giáo viên người Singapore", "Học online hoặc đào tạo sơ sài"], ["Đơn hàng", "Đơn hàng chính thống từ xí nghiệp Singapore", "Qua trung gian, không rõ nguồn gốc"], ["Hỗ trợ tại Singapore", "Văn phòng tại Singapore, hỗ trợ 24/7 tiếng Việt", "Bỏ mặc sau khi xuất cảnh"], ["Cam kết", "Hoàn phí nếu không xuất cảnh đúng hẹn", "Không có cam kết bằng văn bản"]].map((row) => <div className="comparison-row" key={row[0]}><b>{row[0]}</b><span><Check size={15} /> {row[1]}</span><span>{row[2]}</span></div>)}</div><button className="button button-green" onClick={openModal}>Tư vấn ngay</button></div></section>
    <section className="source-section strengths"><div className="container"><h2>Vì Sao Hàng Chục Nghìn Lao Động Tin Chọn Jinmu?</h2><div className="strength-grid">{strengths.map(([title, text], index) => <article key={title}><small>0{index + 1}</small><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><button className="button button-green" onClick={openModal}>Tư vấn ngay</button></div></section>
    <section className="source-section programs" id="programs"><div className="container"><h2>Nhiều Ngành Nghề, Nhiều Lựa Chọn Phù Hợp</h2><div className="program-list">{programs.map(([title, place, salary, image]) => <article className="listing" key={title}><div className="listing-thumb"><span>HOT</span><img src={image} alt={title} /></div><div className="listing-body"><h3>{title}</h3><div className="listing-meta"><span><Users size={14} /> Singapore</span><span><MapPin size={14} /> {place}</span><strong>{salary}</strong></div><p>Chương trình làm việc tại Singapore, lựa chọn phù hợp cho người lao động Việt.</p></div><div className="listing-actions"><button onClick={openModal}>Đăng ký</button><a href="#register-info">Chi tiết</a></div></article>)}</div><button className="button button-outline" onClick={openModal}>Xem tất cả chương trình</button></div></section>
    <section className="source-section cost" id="cost"><div className="container"><h2>Chi Phí Minh Bạch Từ Đầu</h2><p className="section-intro">Toàn bộ chi phí được công khai và ký hợp đồng ngay từ ngày đầu. Bạn biết chính xác mình phải đóng những khoản gì.</p><div className="cost-layout"><img src="https://haiphongconnect.com.vn/wp-content/uploads/2026/06/729186450_122185815974712378_8695870803602476120_n.jpg" alt="Học viên Jinmu" /><div className="cost-table">{[["Phí dịch vụ", "45 triệu VNĐ", "Theo quy định Bộ LĐTBXH"], ["Phí đào tạo nội trú", "45 triệu VNĐ", "Tiếng Singapore, quân tư trang, học liệu, ký túc xá"], ["Chi phí xin Visa", "2,9 triệu VNĐ", "Hồ sơ, thủ tục và Đại sứ quán Singapore"], ["Quỹ cho người lao động", "0,1 triệu VNĐ", "Theo quy định của Bộ"], ["TỔNG", "93 triệu VNĐ", "Cam kết không phát sinh"]].map((row) => <div className="cost-row" key={row[0]}><b>{row[0]}</b><strong>{row[1]}</strong><small>{row[2]}</small></div>)}<p><ShieldCheck size={19} /> Jinmu CAM KẾT KHÔNG thu thêm bất kỳ khoản phí nào ngoài danh sách trên.</p></div></div><button className="button button-green" onClick={openModal}>Tư vấn ngay</button></div></section>
    <section className="source-section roadmap" id="roadmap"><div className="container"><span className="kicker">HÀNH TRÌNH PHÁT TRIỂN</span><h2>Lộ Trình Rõ Ràng<br /><em>(Từ Tư Vấn Đến Xuất Cảnh)</em></h2><div className="roadmap-grid">{roadmap.map((step, index) => <article key={step}><b>0{index + 1}</b><span /><div><h3>{step}</h3><p>{index === 0 ? "Đội ngũ tư vấn viên đánh giá hồ sơ, tư vấn ngành nghề phù hợp với năng lực và mong muốn của bạn." : index === 7 ? "Hỗ trợ trong suốt 3–5 năm hợp đồng: chuyển việc, gia hạn visa, sự cố cá nhân, tái ký." : "Jinmu đồng hành và chuẩn bị chu đáo cho bước tiếp theo."}</p></div></article>)}</div><button className="button button-green" onClick={openModal}>Tư vấn ngay</button></div></section>
    <section className="support-source"><div className="container"><h2>Đồng Hành Cả Khi Bạn Ở Singapore</h2><div className="support-grid"><ul><li><Phone /> Hotline tiếng Việt 24/7 tại Singapore</li><li><MapPin /> Văn phòng đại diện tại 5 thành phố lớn của Singapore</li><li><Clock3 /> Họp định kỳ với học viên 1 lần/tháng tại Singapore</li><li><ShieldCheck /> Hỗ trợ chuyển việc, gia hạn visa, làm thủ tục về nước</li></ul><iframe title="Bản đồ hỗ trợ tại Singapore" src="https://www.google.com/maps?q=Singapore&output=embed" loading="lazy" /></div><button className="button button-green" onClick={openModal}>Tư vấn ngay</button></div></section>
    <footer className="source-footer"><div className="container footer-grid"><div><a className="source-logo footer-logo" href="#top"><span>JINMU</span><b>JINMU</b></a><p>Công ty phái cử nhân lực hàng đầu Việt Nam</p><a href="tel:18006770"><Phone size={15} /> 1800 6770</a><a href="mailto:info@haiphongcorp.com.vn">info@haiphongcorp.com.vn</a></div><div><h4>CÔNG TY</h4><a href="#why">Về chúng tôi</a><a href="#cost">Giấy phép & chứng nhận</a><a href="#roadmap">Hệ thống văn phòng</a></div><div><h4>CHƯƠNG TRÌNH</h4><a href="#programs">Singapore</a><a href="#programs">Chương trình đang tuyển</a><a href="#cost">Chi phí đi Singapore</a></div><div><h4>HỖ TRỢ NGƯỜI LAO ĐỘNG</h4><a href="#register-info">Điều kiện đi Singapore</a><a href="#roadmap">Quy trình đăng ký</a><a href="#support">Hỗ trợ tại Singapore</a></div></div><div className="copyright">© 2026 Jinmu. Bảo lưu mọi quyền.</div></footer>
    <div className="floating-source"><a className="float-phone" href="tel:18006770" aria-label="Gọi 1800 6770"><Phone /></a><a className="float-zalo" href="https://zalo.me/521998241864961527" target="_blank" rel="noreferrer" aria-label="Chat Zalo">Zalo</a><button className="float-consult" onClick={openModal}><Users size={18} /> Đăng ký tư vấn</button></div>
    {modal && <div className="modal-backdrop" onClick={(event) => event.target === event.currentTarget && setModal(false)}><div className="modal-box"><button className="modal-close" onClick={() => setModal(false)} aria-label="Đóng"><X /></button>{success ? <div className="modal-success"><Check /><h2>Đăng ký thành công!</h2><p>Cảm ơn bạn. Chúng tôi sẽ liên hệ lại trong vòng 24 giờ làm việc.</p><button className="button button-outline-green" onClick={() => setModal(false)}>Đóng</button></div> : <><span className="kicker">ĐĂNG KÝ TƯ VẤN NHẬN ƯU ĐÃI</span><h2>Nhận tư vấn đi Singapore</h2><p>Các chuyên viên Jinmu sẽ liên hệ ngay với bạn.</p><LeadForm compact onSuccess={() => setSuccess(true)} /></>}</div></div>}
  </main>;
}
